### ISSUE TITLE
Mass Hysteria in random demo

### ISSUE THREAD

**Issue by bmenaman** [underscoreio/shapeless-guide-code#2] opened 2017-05-11 14:38 UTC
In the exercises branch but not solutions.  It's not obvious to me why this happens - it's trying to create a CNil

**Comment by davegurnell** [comment] 2017-05-12 08:09
The comment on lines 67 to 69 gives a hint as to what's going on:
https://github.com/underscoreio/shapeless-guide-code/blob/exercises/random/src/main/scala/random.scala#L67-L69

The `:+:` instance in the exercises code chooses head and tail with 50/50 probability every time. This is incorrect, because it means there's always a small chance the `CNil` will get chosen:

```
             :+: (100%)
            /          \
Circle (50%)           :+: (50%)
                      /         \
            Rect (25%)           CNil (25%)
```

Your task in the exercise is to modify the probabilities so the probabiliy of choosing `CNil` is 0%:

```
             :+: (100%)
            /          \
Circle (50%)           :+: (50%)
                      /         \
           Rect (100%)           CNil (0%)
```

You can do that by taking into account the length of the coproduct you're expanding in the `:+:` instance. If the coproduct is 1 item long, choose the head with probability 1/1. If it's 2 items long, choose the head with probability 1/2, and so on. By the time you take into account all of the probabilities in the traversal of the coproduct, you'll be assigning each valid subtype (`Circle`, `Rect`, and so on) with equal probability and `CNil` with 0% probability. This will end the hysteria! :)

I hope this clarifies things! It's not a bug in the exercise so I'll close this ticket. If you have any other questions please comment here or post on our books and training Gitter: 

https://gitter.im/underscoreio/scala

Cheers,
Dave

**Closed as completed by davegurnell** 2017-05-12 08:09 UTC

**Comment by bmenaman** [comment] 2017-05-15 17:59
many thanks for all the detail!
